# Employee Dataset Cleaning

This notebook analyzes and cleans a messy employee dataset using Pandas.

## 1. Load and Inspect the Dataset

In [1]:
import pandas as pd

df = pd.read_csv("../data/Messy_Employee_dataset.csv", dtype={"Phone": str})

In [2]:
df.head(10)

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False
5,EMP1005,Alice,Garcia,40.0,Sales-Texas,Inactive,6/10/2020,88642.84,alice.garcia@example.com,-5409003485,Good,False
6,EMP1006,Frank,Jones,NaN,Admin-Nevada,Active,4/3/2020,96288.43,frank.jones@example.com,-4518376063,Good,False
7,EMP1007,Bob,Jones,30.0,Cloud Tech-Florida,Inactive,7/17/2022,94497.91,bob.jones@example.com,-4134327559,Average,True
8,EMP1008,Frank,Davis,35.0,Admin-Nevada,Inactive,12/8/2023,115565.82,frank.davis@example.com,-4177656123,Excellent,True
9,EMP1009,Charlie,Johnson,NaN,DevOps-New York,Active,8/4/2022,76561.88,charlie.johnson@example.com,-8156985699,Excellent,True

In [3]:
print("(rows, columns) =", df.shape)

(rows, columns) = (1020, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   str
 1   First_Name         1020 non-null   str
 2   Last_Name          1020 non-null   str
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   str
 5   Status             1020 non-null   str
 6   Join_Date          1020 non-null   str
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   str
 9   Phone              1020 non-null   str
 10  Performance_Score  1020 non-null   str
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), str(9)
memory usage: 88.8 KB

In [5]:
df.isna().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

## 2. Data Quality Investigation

In this section, we investigate the dataset to identify potential data quality issues before applying any cleaning operations.

We will examine:

- Unique and categorical values
- Value frequencies
- Employee ID uniqueness
- Data types
- Missing values
- Duplicate rows
- Potentially invalid or unexpected values

In [6]:
df["Department_Region"].unique()

<StringArray>
[    'DevOps-California',         'Finance-Texas',          'Admin-Nevada',
    'Cloud Tech-Florida',           'Sales-Texas',       'DevOps-New York',
   'Cloud Tech-New York',           'HR-New York',    'Finance-California',
         'Sales-Florida',       'DevOps-Illinois',     'Cloud Tech-Nevada',
        'Admin-Illinois',   'Cloud Tech-Illinois',        'Sales-Illinois',
        'Finance-Nevada',           'Admin-Texas',        'Sales-New York',
       'Finance-Florida',      'Admin-California',              'HR-Texas',
         'HR-California',             'HR-Nevada',      'Cloud Tech-Texas',
      'Sales-California',           'HR-Illinois',        'Admin-New York',
         'Admin-Florida',            'HR-Florida',          'Sales-Nevada',
      'Finance-New York',        'DevOps-Florida',          'DevOps-Texas',
      'Finance-Illinois', 'Cloud Tech-California',         'DevOps-Nevada']
Length: 36, dtype: str

In [7]:
df["Status"].unique()

<StringArray>
['Active', 'Pending', 'Inactive']
Length: 3, dtype: str

In [8]:
df["Performance_Score"].unique()

<StringArray>
['Average', 'Excellent', 'Good', 'Poor']
Length: 4, dtype: str

In [9]:
df["Remote_Work"].unique()

array([ True, False])

In [10]:
df["Department_Region"].value_counts()

Department_Region
HR-Florida               41
DevOps-California        35
Sales-Nevada             35
Admin-Nevada             34
Admin-California         34
DevOps-Florida           34
DevOps-New York          33
HR-New York              33
Sales-Florida            33
DevOps-Illinois          33
Finance-Illinois         33
Finance-California       32
Sales-California         31
Sales-Illinois           30
Finance-Texas            29
Admin-Illinois           29
Finance-Nevada           29
Cloud Tech-Texas         29
Cloud Tech-California    29
Cloud Tech-Florida       28
DevOps-Texas             27
DevOps-Nevada            27
Sales-New York           26
HR-California            26
Admin-Florida            25
Cloud Tech-New York      24
Finance-Florida          24
HR-Nevada                24
HR-Illinois              24
Sales-Texas              23
HR-Texas                 23
Finance-New York         23
Admin-Texas              22
Admin-New York           22
Cloud Tech-Nevada        20
Cloud Tech-Illinois      16
Name: count, dtype: int64

In [11]:
df["Status"].value_counts()

Status
Pending     356
Active      352
Inactive    312
Name: count, dtype: int64

In [12]:
df["Performance_Score"].value_counts()

Performance_Score
Good         270
Average      267
Excellent    267
Poor         216
Name: count, dtype: int64

In [13]:
df["Remote_Work"].value_counts()

Remote_Work
True     513
False    507
Name: count, dtype: int64

In [14]:
len(df["Employee_ID"].unique())

1020

In [15]:
df["Join_Date"].info()

<class 'pandas.Series'>
RangeIndex: 1020 entries, 0 to 1019
Series name: Join_Date
Non-Null Count  Dtype
--------------  -----
1020 non-null   str
dtypes: str(1)
memory usage: 8.1 KB

In [16]:
df["Phone"].info()

<class 'pandas.Series'>
RangeIndex: 1020 entries, 0 to 1019
Series name: Phone
Non-Null Count  Dtype
--------------  -----
1020 non-null   str
dtypes: str(1)
memory usage: 8.1 KB

In [17]:
df["Phone"].head(15)

0     -1651623197
1     -1898471390
2     -5596363211
3     -3476490784
4     -1586734256
5     -5409003485
6     -4518376063
7     -4134327559
8     -4177656123
9     -8156985699
10    -2720634590
11    -1238296576
12    -2429543164
13    -2669300892
14    -1734206968
Name: Phone, dtype: str

In [18]:
df.duplicated().value_counts()

False    1020
Name: count, dtype: int64

In [19]:
df["Age"].min()

np.float64(25.0)

In [20]:
df["Age"].max()

np.float64(40.0)

## 3. Handling Missing Values

In this section, we will:

- Identify columns containing missing values
- Analyze the missing values
- Decide how each missing value should be handled
- Apply the appropriate cleaning strategy
- Verify the results

In [21]:
df["Age"].median()

np.float64(30.0)

In [22]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [23]:
df["Age"].isna().sum()

np.int64(0)

In [24]:
df["Salary"].median()

np.float64(85547.87)

In [25]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

In [26]:
df["Salary"].isna().sum()

np.int64(0)

In [27]:
df.isna().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

## 4. Data Type Conversion

In this section, we will review the data types of the columns and convert columns whose current types do not match their intended meaning.

In particular, we will:

- Convert `Join_Date` from text to a datetime type
- Review the data type of `Phone`
- Ensure numeric columns use appropriate numeric types
- Verify the resulting data types

In [28]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], format="%m/%d/%Y", errors="coerce")

In [29]:
df["Join_Date"].info()

<class 'pandas.Series'>
RangeIndex: 1020 entries, 0 to 1019
Series name: Join_Date
Non-Null Count  Dtype
--------------  -----
1020 non-null   datetime64[us]
dtypes: datetime64[us](1)
memory usage: 8.1 KB

In [30]:
df["Join_Date"].head(10)

0   2021-04-02
1   2020-07-10
2   2023-12-07
3   2021-11-27
4   2022-01-05
5   2020-06-10
6   2020-04-03
7   2022-07-17
8   2023-12-08
9   2022-08-04
Name: Join_Date, dtype: datetime64[us]

In [31]:
df["Join_Date"].isna().sum()

np.int64(0)

In [32]:
df["Phone"].min()

'-1021923784'

In [33]:
df["Phone"].max()

'-9994973202'

In [34]:
df["Phone"] = df["Phone"].astype(str)

In [35]:
df["Phone"].info()

<class 'pandas.Series'>
RangeIndex: 1020 entries, 0 to 1019
Series name: Phone
Non-Null Count  Dtype
--------------  -----
1020 non-null   str
dtypes: str(1)
memory usage: 8.1 KB

In [36]:
df["Phone"] = df["Phone"].str.strip("-")

In [37]:
df["Phone"].str.len().value_counts()

Phone
10    928
9      78
8      12
7       2
Name: count, dtype: int64

In [38]:
df.loc[df["Phone"].str.len() < 10, "Phone"].to_list()

['164597793',
 '61027768',
 '310303722',
 '54522800',
 '846684549',
 '185106793',
 '794200748',
 '26876810',
 '175370303',
 '894870604',
 '651207048',
 '249685497',
 '812473949',
 '334234257',
 '701765635',
 '41257770',
 '816470899',
 '531312205',
 '136497188',
 '864035532',
 '171302320',
 '116691835',
 '762091842',
 '276420864',
 '822269404',
 '963480796',
 '509754509',
 '305690673',
 '414545634',
 '200053473',
 '23142899',
 '18418619',
 '920981959',
 '882351304',
 '907426087',
 '501716444',
 '40104144',
 '745106633',
 '425488213',
 '104159148',
 '941017589',
 '56435022',
 '3896086',
 '662668216',
 '102724054',
 '704496409',
 '954930595',
 '995765727',
 '368499514',
 '32963346',
 '617893205',
 '61558107',
 '765817389',
 '287675480',
 '440907976',
 '660138240',
 '182727954',
 '142576269',
 '740177508',
 '863218121',
 '155029167',
 '917851384',
 '397739731',
 '687616480',
 '359544293',
 '35624394',
 '869822104',
 '878057214',
 '512080055',
 '507918157',
 '803149981',
 '688285030',
 '63140351',
 '771130620',
 '5155322',
 '752034475',
 '904637659',
 '175096169',
 '388436603',
 '105875255',
 '476921052',
 '817214363',
 '607174810',
 '871827495',
 '184980424',
 '605603566',
 '622072238',
 '652775843',
 '109121721',
 '849378305',
 '586950731',
 '119236036']

In [39]:
df.loc[df["Phone"].str.len() == 10, "Phone"].str[0].value_counts()

Phone
2    122
7    113
4    112
5    109
1     99
6     98
3     95
8     91
9     89
Name: count, dtype: int64

In [40]:
df["Phone"] = df["Phone"].str.zfill(10)

In [41]:
df["Phone"].str.len().value_counts()

Phone
10    1020
Name: count, dtype: int64

In [42]:
df["Phone"].head(10)

0    1651623197
1    1898471390
2    5596363211
3    3476490784
4    1586734256
5    5409003485
6    4518376063
7    4134327559
8    4177656123
9    8156985699
Name: Phone, dtype: str

In [43]:
df["Department_Region"].str.split("-", expand=True).head(10)

            0           1
0      DevOps  California
1     Finance       Texas
2       Admin      Nevada
3       Admin      Nevada
4  Cloud Tech     Florida
5       Sales       Texas
6       Admin      Nevada
7  Cloud Tech     Florida
8       Admin      Nevada
9      DevOps    New York

In [44]:
df[["Department", "Region"]] = df["Department_Region"].str.split("-", expand=True)

In [45]:
df["Age"] = df["Age"].astype(int)
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,30,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,30,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida

In [46]:
columns_order = [
    "Employee_ID", "First_Name", "Last_Name", "Age",
    "Department", "Region", "Status", "Join_Date",
    "Salary", "Email", "Phone", "Performance_Score", "Remote_Work"
]
df = df[columns_order]

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   str
 1   First_Name         1020 non-null   str
 2   Last_Name          1020 non-null   str
 3   Age                1020 non-null   int64
 4   Department         1020 non-null   str
 5   Region             1020 non-null   str
 6   Status             1020 non-null   str
 7   Join_Date          1020 non-null   datetime64[us]
 8   Salary             1020 non-null   float64
 9   Email              1020 non-null   str
 10  Phone              1020 non-null   str
 11  Performance_Score  1020 non-null   str
 12  Remote_Work        1020 non-null   bool
dtypes: bool(1), datetime64[us](1), float64(1), int64(1), str(9)
memory usage: 96.8 KB

In [48]:
df.to_csv("../data/Cleaned_Messy_Employee_dataset.csv", index=False)